### ISSUE TITLE
mixed site URL

### ISSUE THREAD

**Issue by BruegelN** [libigl/libigl.github.io#16]
By default the base URL is http://libigl.github.io/libigl/ (see: [mkdocs.yml](https://github.com/libigl/libigl.github.io/blob/docs/mkdocs.yml#L2)) however this is redirected to https://libigl.github.io/ 
At libigl repo itself the description text says:
"Simple C++ geometry processing library. http://libigl.github.io/libigl/"
but the README contains links without `[...]/libigl/`.
According to the [website](https://libigl.github.io/#attribution) one should use the link: http://libigl.github.io/libigl/
And the links on the website itself are somewhat confusing because only `[...]/libigl/tutorial/` is redirected to `[...]/tutorial/`.
Other links mostly contain `[...]/libigl/` e.g.  go to https://libigl.github.io/#coding-guidelines-and-tips the links for style guide and coding tips link to https://libigl.github.io/libigl/style-guidelines / https://libigl.github.io/libigl/coding-guidelines (broken) and not https://libigl.github.io/style-guidelines / https://libigl.github.io/coding-guidelines (working).
So basically there are many broken links: https://github.com/libigl/libigl.github.io/search?q=libigl.github.io%2Flibigl%2F&unscoped_q=libigl.github.io%2Flibigl%2F

I'd like to fix. Is it ok to replace all links to `http://libigl.github.io/libigl/$something` with `http://libigl.github.io/$something`.
Just creating a redirect like for [libigl/index.html](https://github.com/libigl/libigl.github.io/blob/docs/docs/libigl/index.html) and [libigl/tutorial/index.html](https://github.com/libigl/libigl.github.io/blob/docs/docs/libigl/tutorial/index.html) is not sufficient because e.g. the link to [Example 505 in the FAQ](https://libigl.github.io/faq/) because the `#parameter` will be lost.

Alternatively all the .md file in `docs/` could be moved into `docs/libigl` then http://libigl.github.io/libigl/ would be the correct site URL.

So it's more or less a decision if you want to use http://libigl.github.io/libigl/ or http://libigl.github.io/ (without `[...]/libigl` and the way it currently  is).
Anyway just let me know which of the two versions you prefer so I can to submit a PR :)

**Comment by jdumas** [comment]
Hi,

Good point we need to clean it up a bit. For the website we want to use https://libigl.github.io/, but before we had this website the tutorial page was hosted under https://libigl.github.io/libigl/tutorial, which is why we have this redirection in place to prevent invalid link (for historic reasons).

Now occurrences to https://libigl.github.io/libigl should indeed be replaced by https://libigl.github.io/, and I'll be happy to review a PR for that.

**Comment by BruegelN** [comment]
As it's merged I'll close it for now.
Thanks for being so fast and supportive!
