### ISSUE TITLE
Workflow for developing website

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl.github.io#9]
Since the .html and the .md live in different branches, I'm struggling to find a good workflow for developing the library.

Suppose I've checked out the docs branch and then make a change to tutorial.md, what's the best practice for previewing my change on the .html website?

**Comment by jdumas** [comment]
You can preview locally the website on your computer by running a local python server with `python3 -m mkdocs serve` from the root folder. There is also a one-to-one mapping between the file path in the `docs/` folder and the urls on the website, so it should be easy to find which is which. When browsing the website you can also click the "edit" button on the top right and it will open the github text editor where you can do a quick correction and push/create a PR for it.

**Comment by jdumas** [comment]
@alecjacobson any interrogation left on this issue, or can we close it?
